### ISSUE TITLE
write() function with encoding="cp1047" uses wrong code points for square brackets

### ISSUE THREAD

**Issue by pjfarleyiii** [daveyc/pyzfile#2]
Writing records to a z/OS PDS member the square bracket characters are stored as X'BA' and X'BB' rather than X'AD' and X'BD'.

I haven't checked the other "problematic" characters yet (cent sign, not sign, caret, unbroken and broken vertical bars).

It is kind of difficult to write json output to a z/OS file without the correct square bracket characters.  Is there any other encoding that will give correct square brackets in a z/OS file?

**Comment by daveyc** [comment]
Can you supply your environment variables? From the shell run the following command:
```
env | sort
```

**Comment by daveyc** [comment]
@pjfarleyiii I can't recreate this problem. The following code snippet:

```python
from pyzfile import *
import json
recs = ['record number one', 'record number two', 'record number three']
try:
        with ZFile("//CNTL(PYZJSON)", "w", encoding='cp1047') as file:
            file.write(json.dumps(recs))
except ZFileError as e:
        print(e)
```
Produces the expected results
```
VIEW       TS8004.CNTL(PYZJSON) - 01.00                            Columns 
Command ===>                                                          Scrol
****** ********************************* Top of Data **********************
000001 ["record number one", "record number two", "record number three"]   
       A798899849A98894998764798899849A98894AA9764798899849A98894A89887B000
       DF95369405442590655FB0F95369405442590366FB0F9536940544259038955FD000
---------------------------------------------------------------------------
****** ******************************** Bottom of Data ********************
```

**Comment by pjfarleyiii** [comment]
env | sort -- text file attached (my ID is masked)

[system.txt](https://github.com/daveyc/pyzfile/files/11006920/system.txt)

Try this instead ("Zxxxxx" is my masked userid on this system):

```
from pyzfile import *
recs = ['[', 'field1: record number one', 'field2: record number two', 'field3: record number three', ']']
outfile = "//'Zxxxxx.CONTEST(TESTSQBR)'"
try:
        with ZFile(outfile, "w", encoding='cp1047') as file:
            for elem in recs:
                file.write(elem + "\n")
except ZFileError as e:
        print(e)
```

ISPF Browse of the resulting member:

```
 ISRBROBA DSLIST .CONTEST(TESTSQBR)                 Line 0000000001 Col 001 080 
 Command ===>                                                  Scroll ===> CSR  
Ý                                                                               
B4444444444444444444444444444444444444444444444444444444444444444444444444444444
A0000000000000000000000000000000000000000000000000000000000000000000000000000000
 ------------------------------------------------------------------------------ 
field1: record number one                                                       
88898F7498899849A988949984444444444444444444444444444444444444444444444444444444
695341A0953694054425906550000000000000000000000000000000000000000000000000000000
 ------------------------------------------------------------------------------ 
field2: record number two                                                       
88898F7498899849A98894AA94444444444444444444444444444444444444444444444444444444
695342A0953694054425903660000000000000000000000000000000000000000000000000000000
 ------------------------------------------------------------------------------ 
field3: record number three                                                     
88898F7498899849A98894A898844444444444444444444444444444444444444444444444444444
695343A0953694054425903895500000000000000000000000000000000000000000000000000000
 ------------------------------------------------------------------------------ 
¨                                                                               
B4444444444444444444444444444444444444444444444444444444444444444444444444444444
B0000000000000000000000000000000000000000000000000000000000000000000000000000000
```

**Comment by daveyc** [comment]
@pjfarleyiii I ran your code and it worked as expected. I suspect this may be due to the code page you're using for your editor. Are you using the ISPF editor? The general ROT for code pages for source code that use enhanced ASCII and file tagging is to use ISO8859-1. ISPF supports editing files in ISO8859-1 or UTF encoding. Are you by any chance using IBM-037? Also, it's interesting that you are hand crafting your own JSON and not using the python `json` package. Is that intentional?

**Comment by pjfarleyiii** [comment]
The original python code was written on a Windows box in EditPlus V5, so I guess cp1252(?) in z/OS terms.  Then it is uploaded to the z/OS USS file system using ```zowe files ul ftu script.py /z/zxxxxx/script.py```.  If I use ```od -X``` to display the python file when logged into USS on the z/OS system I see this, which is plainly EBCDIC:

```
0000000000          86999694        4097A8A9        86899385        40899497
0000000020          9699A340        5C158994        979699A3        4091A296
0000000040          95159985        83A2407E        40AD7DAD        7D6B407D  <== 7DAD7D here is '['
0000000060          86898593        84F17A40        99858396        99844095
0000000100          A4948285        99409695        857D6B40        7D868985
0000000120          9384F27A        40998583        96998440        95A49482
0000000140          859940A3        A6967D6B        407D8689        859384F3
0000000160          7A409985        83969984        4095A494        82859940
0000000200          A3889985        857D6B40        7DBD7DBD        1596A4A3  <== 7DBD7D here is ']'
0000000220          86899385        407E407F        61617DE9        F0F2F4F4
0000000240          F64BC3D6        D5E3C5E2        E34DE3C5        E2E3E2D8
0000000260          C2D95D7D        7F15A399        A87A1540        40404040
0000000300          404040A6        89A38840        E9C68993        854D96A4
0000000320          A3868993        856B407F        A67F6B40        85958396
0000000340          84899587        7E7D8397        F1F0F4F7        7D5D4081
0000000360          A2408689        93857A15        40404040        40404040
0000000400          40404040        86969940        85938594        40899540
0000000420          998583A2        7A154040        40404040        40404040
0000000440          40404040        40408689        93854BA6        9989A385
0000000460          4D859385        94404E40        7FE0957F        5D1585A7
0000000500          838597A3        40E9C689        9385C599        99969940
0000000520          81A24085        7A154040        40404040        40409799
0000000540          8995A34D        855D0000
```

The python file was untagged for my initial test of the example sccript, but even after I tagged it as IBM1047 the results in the PDS are the same.

```t IBM-1047    T=on  -rw-r--r--   1 Zxxxxx   IPGROUP      358 Mar 17 18:02 testsqbr2.py```

It is not intended to be actual "json" output, but a specific "json-like" output required by the contest challenge rules.  I greatly simplified the format of the example for this report to you, but that's the gist of it.

So you are saying upload python code in ISO8859-1 and do NOT convert it to an IBM code page and it should work?

I did try that, uploaded with ```zowe files ul ftu script.py /z/zxxxxx/script.py --ec 819``` and tagged the python file as ISO8859-1 and the results in the output PDS were the same - X'BA' and X'BB' for the square brackets.  In the ISO8859-1 python file the square brackets are X'5B' and X'5D'.

**Comment by daveyc** [comment]
@pjfarleyiii I've changed the script to accept an encoding as a program argument and not matter what I specify it works. I can only assume that this is either a user error or environmental. The `pyzfile` package uses standard python encoding functions which have been extended with EBCDIC codecs which are shipped as part of IBMs Python SDK. Try using different encodings and let me know how you go. 

```python
from pyzfile import *
import sys
recs = ['[', 'field1: record number one', 'field2: record number two', 'field3: record number three', ']']
outfile = "//CNTL(TESTSQBR)"
try:
    with ZFile(outfile, "w", encoding=sys.argv[1]) as file:
       for elem in recs:
          file.write(elem + "\n")
except ZFileError as e:
    print(e)
```

**Comment by pjfarleyiii** [comment]
@daveyc Where can I find a list of the EBCDIC codecs supported by the IBM python SDK?  Or is it only the ones supported by the C library?  And if C library, which one?  The one that runs in z/OS batch (for which there are manuals) or the one you can only get for USS execution?  I still haven't seen PDF manuals specific to that new "clang" version.

Also, could this be related to the fact that you have said pyzfile requires python 3.10 but the z/Xplore z/OS system is only running V3.9?

**Comment by daveyc** [comment]
You can find a list of supported codecs on the [PyPi page](https://pypi.org/project/ebcdic/). As you are running an unsupported (different build system) version of Python I will leave this open for a short time and then close as my test cases all pass. I suggest you reach out the the maintainers of `z/Xplore` and ask them to upgrade Python. Python3.9 is no longer supported for bugfixes. See the [support](https://devguide.python.org/versions/) page. Alternatively, you can download the pax yourself.

**Comment by pjfarleyiii** [comment]
Unfortunately the upgrade to python 3.10 will probably only be available on z/Xplore when the infrastructure they model on is upgraded to z/OS V2.5 (or maybe not even then).  Downloading the pax isn't an option, "students" on z/Xplore have very limited disk quotas on purpose - they are not supposed to install any software on their own, they only get to use what is already installed on the system to solve the learning challenges / exercises.

As for the codecs available on this system:

```
 > python3
Python 3.9.2 (heads/pyz_dev-3.9:91bcbd3bc6, Apr 15 2021, 02:47:09) on zos
Type "help", "copyright", "credits" or "license" for more information.
>>> import ebcdic
>>> ebcdic.ignored_codec_names()
['cp037', 'cp1047', 'cp1097', 'cp1140', 'cp1141', 'cp1142', 'cp1143', 'cp1144', 'cp1145', 'cp1146', 'cp1147', 'cp1148', 'cp1149', 'cp273', 'cp290', 'cp424', 'cp500', 'cp838', 'cp870', 'cp875']
```

So it looks like cp1047 isn't using the ```ebcdic``` package translation, but one of the the system codecs instead.

Go ahead and close this issue, I will wait for the z/Xplore system to get updated before I depend on pyzfile there.

**Comment by daveyc** [comment]
I just tried with Python3.9 and that worked. You're environment seems at play. Try opening the file as QSAM binary like so:

```python
try:
        with ZFile(outfile, "wb, type=record, noseek", encoding='cp1047') as file:
            for elem in recs:
                file.write(elem + "\n")
except ZFileError as e:
        print(e)
```

**Comment by pjfarleyiii** [comment]
No difference using "wb, type=record, noseek", still generates X'BA' and X'BB' for the square brackets.  This was with an EBCDIC-encoded (IBM1047) and tagged source program.  Using a source program encoded and tagged with ISO8859-1 generates the same wrong result.

**Comment by daveyc** [comment]
I've also tested with Python 3.11 and that works. What kind of system is z/Xplore running. Is this an emulator running on a PC? Can you test this on your work machine?

**Comment by pjfarleyiii** [comment]
I *think* the z/Xplore system is running on x86 hardware, not z hardware, but I don't know what kind of x86 hardware.  It might well be an anonymous "cloud" machine somewhere in the IBM cloud.  One of the z/Xplore challenges in the 2021 year-end contest included discovering and reporting information about the system itself.  This was the output for that part of that challenge:

```host:zCX platform:s390x os:Ubuntu```

So possibly a zCX container running Ubuntu on a z/OS LPAR (or a z/Linux VM?) somewhere, but no obvious way to prove or disprove what the "real" hardware actually is.

I cannot run any python code on my work machine because there is no python installed there at all (nothing from Rocket or CoZ either).

I do have access to another z/OS LPAR that is running on real z hardware and also has python 3.11 and pyzfile installed, and on that system the square bracket conversion works the right way - X'AD'-X'BD'.  So this must be something environmental on the z/Xplore system.

I will close this issue myself and advise my contact at z/Xplore that they probably shouldn't publicize pyzfile for actual contests or challenges on their system until the next system upgrade (probably to z/OS 2.5, if my information is correct, maybe later this year).  Hopefully the python environment on the upgraded system will be less trouble.

Thanks for all your attention and work.
